repos:
  -   repo: https://github.com/astral-sh/ruff-pre-commit
      rev: 'v0.5.0'
      hooks:
      -   id: ruff
  -   repo: https://github.com/PyCQA/isort
      rev: 5.13.2 # (Актуальная версия isort)
      hooks:
      -   id: isort
          name: isort (grid-style)
