repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.4
  hooks:
# STEP 1: First, format the code.
    - id: ruff-format
# STEP 2: Look for errors and correct them.
    - id: ruff
      args: ["--fix", "--exit-non-zero-on-fix"]
